naverpay.client-id=HN3GGCMDdTgGUfl0kFCo
naverpay.client-secret=ftZjkkRNMR
naverpay.chain-id=TUxwbzJsVVJ4b2x
naverpay.approve-url=https://dev-pay.paygate.naver.com/naverpay-partner/naverpay/payments/v2.2/apply/payment

upload.notice.path=D:/DEV06/workspace_git_ict06/ict06_mid_pj/upload/notice/
upload.community.path=D:/DEV06/workspace_git_ict06/ict06_mid_pj/upload/community/

upload.restaurant.path=D:/DEV06/workspace_git_ict06/ict06_mid_pj/src/main/webapp/resources/images/admin/restaurant/
upload.accommodation.path=D:/DEV06/workspace_git_ict06/ict06_mid_pj/src/main/webapp/resources/images/admin/accommodation/