-- 관리자용 축제 메뉴 사용을 위한 쿼리 모음
-- 축제 목록 조회 (페이징용) 
SELECT *
  FROM PLACE p
  JOIN FESTIVAL f 
    ON p.place_id = f.festival_id;

-- 키워드가 포함된 축제 검색 : p.Name, p.Address, f.Description 중 한 개라도 키워드와 일치하면 도출   
SELECT *
  FROM PLACE p
  JOIN FESTIVAL f 
    ON p.place_id = f.festival_id
 WHERE p.Name LIKE '%신나는%'
    OR p.ADDRESS LIKE '%서울%'
    OR f.DESCRIPTION LIKE '%신나는%';

-- 축제 상세 조회
SELECT * 
  FROM FESTIVAL
 WHERE FESTIVAL_ID = 417;

-- 축제 티켓 조회
SELECT
	    ticket_id,
	    festival_id,
	    ticket_type,
	    price,
	    stock,
	    description
  FROM  FESTIVAL_TICKET
 WHERE  festival_id = 1009;

-----------------------------------------
-- 축제 등록 시 문제가 생길 때 체크 
-- PLACE 테이블의 place_id 최댓값 확인
SELECT MAX(place_id) FROM PLACE;

-- SEQ_PLACE의 최댓값 확인
SELECT SEQ_PLACE.NEXTVAL FROM DUAL;

-- SEQ_PLACE.NEXTVAL이 현재 PLACE 테이블이의 최대 place_id가 동일한 크기가 아닐 때 적용
DROP SEQUENCE SEQ_PLACE;
CREATE SEQUENCE SEQ_PLACE
START WITH 1008 -- 최대 place_id + 1 (이거 상수만 넣을 수 있음. 주의!)
INCREMENT BY 1;

-- SEQ_TICKET의 최댓값 확인
SELECT SEQ_TICKET.NEXTVAL FROM DUAL;

--------------------------------------------
-- 테이블 리셋 필요 시 사용할 drop 문
-- 1. 자식 테이블
DROP TABLE SEARCH_HISTORY;
DROP TABLE FAVORITE;
DROP TABLE NOTICE;
DROP TABLE INQUIRY;
DROP TABLE POINT;
DROP TABLE POINT_POLICY;
DROP TABLE SURVEY;
DROP TABLE FAQ;
DROP TABLE IMAGE_STORE;
DROP TABLE REVIEW;
DROP TABLE FESTIVAL_TICKET;
DROP TABLE COMMUNITY_COMMENT; 
DROP TABLE COMMUNITY; 


-- 2. 거래 관련 테이블 (결제는 예약을 참조하므로 결제 먼저 삭제)
DROP TABLE PAYMENT;
DROP TABLE RESERVATION;

-- 3. 장소 상세 테이블 (부모인 PLACE를 참조하므로 먼저 삭제)
DROP TABLE RESTAURANT;
DROP TABLE ACCOMMODATION;
DROP TABLE FESTIVAL;

-- 4. 최상위 부모 테이블
DROP TABLE PLACE;
DROP TABLE MEMBER;

-- 5. 시퀀스 삭제
DROP SEQUENCE SEQ_PLACE;
DROP SEQUENCE SEQ_TICKET;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_IMAGE;
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_INQUIRY;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_POST;
DROP SEQUENCE SEQ_COMMENT;
DROP SEQUENCE SEQ_SURVEY;
DROP SEQUENCE SEQ_POINT;
DROP SEQUENCE SEQ_FAVORITE;
DROP SEQUENCE SEQ_SEARCH;
DROP SEQUENCE SEQ_RES;
DROP SEQUENCE SEQ_PAY;

-- 강제 삭제 필요 시 아래 사용 
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE PLACE CASCADE CONSTRAINTS;

-- 멤버 테이블 insert 쿼리
INSERT ALL
INTO MEMBER VALUES ('admin','1234','admin@test.com','관리자',TO_DATE('1985-01-01','YYYY-MM-DD'),'M','010-0000-0000','서울 강남구',100000,'ADMIN','ACTIVE',SYSTIMESTAMP, SYSTIMESTAMP)
INTO MEMBER VALUES ('user01','1234','user01@test.com','김민수',TO_DATE('1995-03-10','YYYY-MM-DD'),'M','010-1111-1111','서울 송파구',1200,'USER','ACTIVE',SYSTIMESTAMP, SYSTIMESTAMP)
INTO MEMBER VALUES ('user02','1234','user02@test.com','이서연',TO_DATE('1998-07-21','YYYY-MM-DD'),'F','010-2222-2222','서울 강서구',850,'USER','ACTIVE',SYSTIMESTAMP, SYSTIMESTAMP)
INTO MEMBER VALUES ('user03','1234','user03@test.com','박지훈',TO_DATE('1993-11-04','YYYY-MM-DD'),'M','010-3333-3333','성남시 분당구',4500,'USER','ACTIVE',SYSTIMESTAMP, SYSTIMESTAMP)
INTO MEMBER VALUES ('user04','1234','user04@test.com','최유진',TO_DATE('1999-02-14','YYYY-MM-DD'),'F','010-4444-4444','인천 연수구',320,'USER','ACTIVE',SYSTIMESTAMP, SYSTIMESTAMP)
INTO MEMBER VALUES ('user05','1234','user05@test.com','정하늘',TO_DATE('1990-06-09','YYYY-MM-DD'),'M','010-5555-5555','부산 해운대구',9800,'USER','ACTIVE',SYSTIMESTAMP, SYSTIMESTAMP)
INTO MEMBER VALUES ('user06','1234','user06@test.com','한지민',TO_DATE('1997-04-22','YYYY-MM-DD'),'F','010-6666-6666','대구 수성구',760,'USER','ACTIVE',SYSTIMESTAMP, SYSTIMESTAMP)
INTO MEMBER VALUES ('user07','1234','user07@test.com','윤태호',TO_DATE('1994-08-30','YYYY-MM-DD'),'M','010-7777-7777','대전 서구',1500,'USER','ACTIVE',SYSTIMESTAMP, SYSTIMESTAMP)
INTO MEMBER VALUES ('user08','1234','user08@test.com','송다은',TO_DATE('2000-12-12','YYYY-MM-DD'),'F','010-8888-8888','광주 북구',2400,'USER','ACTIVE',SYSTIMESTAMP, SYSTIMESTAMP)
INTO MEMBER VALUES ('user09','1234','user09@test.com','강도윤',TO_DATE('1996-09-17','YYYY-MM-DD'),'M','010-9999-9999','울산 남구',500,'USER','ACTIVE',SYSTIMESTAMP, SYSTIMESTAMP)
SELECT * FROM DUAL;